<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260405190806 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Domain event audit table and Symfony Messenger doctrine transport tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE domain_event (id UUID NOT NULL, name VARCHAR(190) NOT NULL, aggregate_id VARCHAR(36) NOT NULL, event_id VARCHAR(36) NOT NULL, occurred_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, body JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX domain_event_aggregate_id_idx ON domain_event (aggregate_id)');
        $this->addSql('CREATE INDEX domain_event_name_idx ON domain_event (name)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE domain_event');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
