<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616201857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bank (name VARCHAR(255) NOT NULL, name_normalized VARCHAR(255) NOT NULL, short_name VARCHAR(50) NOT NULL, id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, stored_object_key VARCHAR(512) DEFAULT NULL, stored_object_mime_type VARCHAR(64) DEFAULT NULL, stored_object_byte_size INT DEFAULT NULL, stored_object_content_hash VARCHAR(64) DEFAULT NULL, logo_media_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        // Byte-wise COLLATE "C" on the keyset sort columns (byte-ordered uniqueness + correct cursor
        // pagination). Doctrine's entity mapping does not model collation, so it is applied here, before
        // the unique indices, exactly as the pre-squash schema did; the comparator ignores it, so
        // `make db.diff` stays empty. See SortFieldMapIndexContractTest.
        $this->addSql('ALTER TABLE bank ALTER COLUMN name_normalized TYPE VARCHAR(255) COLLATE "C"');
        $this->addSql('ALTER TABLE bank ALTER COLUMN short_name TYPE VARCHAR(50) COLLATE "C"');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D860BF7AE1B35095 ON bank (name_normalized)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D860BF7A3EE4B093 ON bank (short_name)');
        $this->addSql('CREATE INDEX IDX_D860BF7ABAAE86A3 ON bank (logo_media_id)');
        $this->addSql('CREATE INDEX idx_bank_created_at_id ON bank (created_at, id)');
        $this->addSql('CREATE INDEX idx_bank_updated_at_id ON bank (updated_at, id)');
        $this->addSql('CREATE TABLE bank_account (bank_id UUID NOT NULL, holder_name VARCHAR(255) NOT NULL, iban VARCHAR(34) NOT NULL, bic VARCHAR(11) DEFAULT NULL, alias VARCHAR(100) DEFAULT NULL, currency VARCHAR(3) NOT NULL, status TEXT NOT NULL, id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53A23E0AFAD56E62 ON bank_account (iban)');
        $this->addSql('CREATE INDEX IDX_53A23E0A11C8FB41 ON bank_account (bank_id)');
        $this->addSql('CREATE TABLE media (content_hash VARCHAR(64) NOT NULL, mime_type VARCHAR(64) NOT NULL, byte_size INT NOT NULL, raw_bytes BYTEA NOT NULL, id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX media_content_hash_uniq ON media (content_hash)');
        $this->addSql('CREATE TABLE bank_count (id SMALLINT DEFAULT 1 NOT NULL, total INT DEFAULT 0 NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event_store (sequence BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id UUID NOT NULL, aggregate_id UUID NOT NULL, aggregate_type VARCHAR(120) NOT NULL, aggregate_version INT NOT NULL, event_name VARCHAR(190) NOT NULL, event_version SMALLINT DEFAULT 1 NOT NULL, payload JSONB NOT NULL, metadata JSONB NOT NULL, tenant_id UUID DEFAULT NULL, occurred_on TIMESTAMP(0) WITH TIME ZONE NOT NULL, recorded_on TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (sequence))');
        $this->addSql('CREATE UNIQUE INDEX event_store_event_id_uniq ON event_store (event_id)');
        $this->addSql('CREATE UNIQUE INDEX event_store_stream_version_uniq ON event_store (tenant_id, aggregate_id, aggregate_version)');
        $this->addSql('CREATE INDEX event_store_aggregate_idx ON event_store (aggregate_type, aggregate_id, sequence)');
        $this->addSql('CREATE INDEX event_store_name_idx ON event_store (event_name, sequence)');
        $this->addSql('CREATE INDEX event_store_recorded_idx ON event_store (recorded_on)');
        $this->addSql('CREATE TABLE handled_domain_event (event_id VARCHAR(36) NOT NULL, handler VARCHAR(190) NOT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (event_id, handler))');
        $this->addSql('CREATE TABLE projection_checkpoint (name VARCHAR(120) NOT NULL, last_sequence BIGINT DEFAULT 0 NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (name))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE bank ADD CONSTRAINT FK_D860BF7ABAAE86A3 FOREIGN KEY (logo_media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A11C8FB41 FOREIGN KEY (bank_id) REFERENCES bank (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bank DROP CONSTRAINT FK_D860BF7ABAAE86A3');
        $this->addSql('ALTER TABLE bank_account DROP CONSTRAINT FK_53A23E0A11C8FB41');
        $this->addSql('DROP TABLE bank');
        $this->addSql('DROP TABLE bank_account');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE bank_count');
        $this->addSql('DROP TABLE event_store');
        $this->addSql('DROP TABLE handled_domain_event');
        $this->addSql('DROP TABLE projection_checkpoint');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
