#!/usr/bin/env bash
# =============================================================================
# trust-local.sh — the PRIVILEGED client-trust steps for the local prod deploy
# =============================================================================
#
# Run AFTER `make deploy.local` (which exports the CA root). Must run as root:
#
#     sudo make deploy.local.trust          # or: sudo bash scripts/deploy/trust-local.sh
#
# Preview WITHOUT changing anything (no sudo needed):
#
#     bash scripts/deploy/trust-local.sh --dry-run
#
# Do all the root-requiring trust wiring in one auditable command, targeting the
# INVOKING user (via $SUDO_USER), not root. THIS WRITES FILES OUTSIDE THE REPO,
# on your OS — see the "Will modify" banner it prints. Steps:
#   1. /etc/hosts        — add `127.0.0.1 $SERVER_NAME` if missing
#   2. system trust      — install the CA into the OS bundle (curl/openssl/Node)
#   3. Chromium/NSS      — add the CA to the invoking user's ~/.pki/nssdb
#                          (Chrome/Chromium/Edge); installs certutil if needed
#
# Firefox keeps its OWN store and cannot be scripted here — import via its GUI
# (see docs/erpify-local-test-deployment.md step 4).
#
# Why not `sudo make deploy.local`? Running the whole build/up/migrate pipeline
# as root creates root-owned artifacts and would trust the CA in root's profile
# (HOME=/root), not yours — so the browser still wouldn't trust it. Keep the
# deploy unprivileged; isolate the few root steps here.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

ENV_FILE="${PROD_ENV_FILE:-.env.prod.local}"
CA_OUT="erpify-local-root-ca.crt"
SYS_CA_DIR="/usr/local/share/ca-certificates"

DRY_RUN=0

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info()    { echo -e "${BLUE}ℹ ${*}${NC}"; }
log_success() { echo -e "${GREEN}✔ ${*}${NC}"; }
log_warning() { echo -e "${YELLOW}⚠ ${*}${NC}"; }
log_error()   { echo -e "${RED}✖ ${*}${NC}" >&2; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) grep -E '^# ' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) log_error "Unknown option: $1"; exit 1 ;;
    esac
done

# —— Root required (except for --dry-run preview) ——————————————————————————
if [[ $DRY_RUN -eq 0 && "${EUID:-$(id -u)}" -ne 0 ]]; then
    log_error "This step needs root. Re-run:  sudo make deploy.local.trust"
    log_error "(or preview first, no sudo:  bash scripts/deploy/trust-local.sh --dry-run)"
    exit 1
fi

# —— Resolve the invoking (non-root) user for the per-user NSS store ————————
TARGET_USER="${SUDO_USER:-$(logname 2>/dev/null || true)}"
TARGET_HOME=""
if [[ -z "$TARGET_USER" || "$TARGET_USER" == "root" ]]; then
    TARGET_USER=""
    [[ $DRY_RUN -eq 0 ]] && log_warning "No non-root invoker (SUDO_USER unset) — Chromium/NSS trust will be skipped."
else
    TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
fi
[[ -z "$TARGET_HOME" ]] && TARGET_HOME="${HOME:-/root}"
NSS_DB="${TARGET_HOME}/.pki/nssdb"

# —— Server name + CA file ————————————————————————————————————————————————
SERVER_NAME="$(grep -E '^SERVER_NAME=' "$ENV_FILE" 2>/dev/null | head -n1 | cut -d= -f2- | tr -d '"' | xargs || true)"
SERVER_NAME="${SERVER_NAME:-erpify.local}"
HOSTS_LINE="127.0.0.1   ${SERVER_NAME}"
NSS_NICK="${SERVER_NAME} Local CA"

if [[ ! -f "$CA_OUT" ]]; then
    log_error "$CA_OUT not found. Run 'make deploy.local' first (it exports the CA root)."
    exit 1
fi

# —— Disclosure: files changed OUTSIDE the repo, on this OS ————————————————
echo
log_warning "This writes to files OUTSIDE the repo, on your system:"
echo    "    • /etc/hosts                          → append \"${HOSTS_LINE}\""
echo    "    • ${SYS_CA_DIR}/${CA_OUT}   → new file (the CA, public cert)"
echo    "    • /etc/ssl/certs/ca-certificates.crt  → regenerated by update-ca-certificates"
if [[ -n "$TARGET_USER" ]]; then
    echo "    • ${NSS_DB}/{cert9.db,key4.db,pkcs11.txt}   → user '${TARGET_USER}' Chromium/NSS trust"
fi
echo    "    • system package 'libnss3-tools'      → apt-installed only if certutil is missing"
echo    "  (Firefox is NOT touched — its own store needs a manual GUI import, step 4.)"
echo

if [[ $DRY_RUN -eq 1 ]]; then
    log_info "[DRY-RUN] No changes made. Re-run with sudo to apply:  sudo make deploy.local.trust"
    exit 0
fi

# —— 1. /etc/hosts ————————————————————————————————————————————————————————
if grep -qE "[[:space:]]${SERVER_NAME}([[:space:]]|\$)" /etc/hosts 2>/dev/null; then
    log_success "/etc/hosts already resolves ${SERVER_NAME} (unchanged)."
else
    printf '%s\n' "$HOSTS_LINE" >> /etc/hosts
    log_success "Wrote /etc/hosts: ${HOSTS_LINE}"
fi

# —— 2. System trust (curl / openssl / Node) ——————————————————————————————
if command -v update-ca-certificates >/dev/null 2>&1; then
    install -m 0644 "$CA_OUT" "${SYS_CA_DIR}/${CA_OUT}"
    update-ca-certificates >/dev/null
    log_success "Installed CA into ${SYS_CA_DIR}/ and refreshed /etc/ssl/certs (curl/openssl/Node)."
else
    log_warning "update-ca-certificates not found (non-Debian host?). Install the CA into the OS trust store manually."
fi

# —— 3. Chromium/NSS trust for the invoking user ——————————————————————————
if [[ -n "$TARGET_USER" ]]; then
    if ! command -v certutil >/dev/null 2>&1; then
        log_info "Installing libnss3-tools (provides certutil)..."
        if command -v apt-get >/dev/null 2>&1; then
            if ! { apt-get update -qq && apt-get install -y -qq libnss3-tools; }; then
                log_warning "apt install failed — install libnss3-tools manually."
            fi
        else
            log_warning "No apt-get — install certutil (libnss3-tools / nss) manually, then re-run."
        fi
    fi
    if command -v certutil >/dev/null 2>&1; then
        runuser -u "$TARGET_USER" -- mkdir -p "$NSS_DB"
        runuser -u "$TARGET_USER" -- bash -c "[ -f '${NSS_DB}/cert9.db' ] || certutil -d sql:'${NSS_DB}' -N --empty-password"
        runuser -u "$TARGET_USER" -- certutil -d sql:"$NSS_DB" -D -n "$NSS_NICK" 2>/dev/null || true
        runuser -u "$TARGET_USER" -- certutil -d sql:"$NSS_DB" -A -t "C,," -n "$NSS_NICK" -i "./${CA_OUT}"
        log_success "Wrote ${NSS_DB} — Chrome/Chromium/Edge trust for user '${TARGET_USER}'."
    fi
fi

# —— Done ——————————————————————————————————————————————————————————————————
echo
log_success "Privileged trust steps complete."
echo "Firefox keeps its own store — import ./${CA_OUT} via about:preferences#privacy"
echo "  → View Certificates → Authorities → Import → 'Trust this CA to identify websites'."
echo "Then restart the browser and open:  https://${SERVER_NAME}"
