<?php

declare(strict_types=1);

namespace Erpify\Tests\Unit\Shared\Architecture;

use Erpify\Tests\Support\ScheduleConsumption;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * Static gate over the one property that makes "this control is scheduled" falsifiable: every
 * `#[AsSchedule]` in `api/src` must have its derived `scheduler_*` transport named in a `messenger:consume`
 * command of BOTH root compose files.
 *
 * Nothing else in the repo checks it, and nothing at runtime complains. Symfony's `AddScheduleMessengerPass`
 * creates `messenger.transport.scheduler_<name>` from the attribute alone, so the schedule registers, the
 * container compiles, deptrac passes and every test is green while the ticks are generated by nobody and
 * consumed by nobody. A scheduled compliance control that ships dead is indistinguishable from one that
 * ships working right up until the day it was supposed to catch something.
 *
 * What a green run does NOT prove, and the distinction matters because this gate is the evidence behind a
 * requirement that alarms have to arrive: it proves a transport name appears in a consume command. It does
 * not prove the worker is running, that the service is deployed, that `--time-limit` is sane, that the
 * schedule's period is right, or that anything ever reached a log. Presence of the name is the floor, not
 * the guarantee.
 *
 * The derivation rules live in {@see ScheduleConsumption} and their falsifiability in
 * {@see ScheduleConsumptionRulesGateTest}; this class is the assertions over the real tree.
 *
 * @internal
 */
#[CoversNothing]
final class ScheduleConsumptionGateTest extends TestCase
{
    public const string FAILURE_PREAMBLE
        = 'A schedule proves nothing by declaring itself. Symfony creates its transport from the attribute, '
        . 'so a schedule whose transport no `messenger:consume` command names compiles, registers and ships '
        . 'DEAD with every gate green — which is why "it is scheduled" is not a claim this repo lets anyone '
        . 'make without this check.';

    #[Test]
    public function theTreeDeclaresAtLeastOneSchedule(): void
    {
        // Without this the gate is vacuous: an empty sweep satisfies every assertion below, so a broken
        // attribute pattern or a moved source root would report success while checking nothing at all.
        $this->assertNotEmpty(
            ScheduleConsumption::declaredScheduleNames(),
            'No #[AsSchedule] was found under api/src. Either the tree lost every schedule or this gate '
            . 'stopped being able to see them — both make its green meaningless.',
        );
    }

    #[Test]
    #[DataProvider('composeFiles')]
    public function everyDeclaredScheduleHasItsTransportConsumed(string $composeFile): void
    {
        $path = $this->composeDirectory() . '/' . $composeFile;
        $consumed = ScheduleConsumption::consumedTransportsIn($path);

        $missing = [];

        foreach (ScheduleConsumption::declaredScheduleNames() as $scheduleName) {
            $transport = ScheduleConsumption::transportOf($scheduleName);

            if (!\in_array($transport, $consumed, true)) {
                $missing[] = $transport;
            }
        }

        $this->assertSame([], $missing, self::FAILURE_PREAMBLE . "\n" . \sprintf(
            "These schedule transports are not consumed in %s:\n  %s\nAdd them to a `messenger:consume` "
            . 'command there.',
            $composeFile,
            \implode("\n  ", $missing),
        ));
    }

    #[Test]
    #[DataProvider('composeFiles')]
    public function noConsumeCommandNamesATransportNoScheduleProduces(string $composeFile): void
    {
        $unbacked = ScheduleConsumption::unbackedSchedulerTransportsIn(
            $this->composeDirectory() . '/' . $composeFile,
            ScheduleConsumption::declaredScheduleNames(),
        );

        $this->assertSame([], $unbacked, \sprintf(
            "These scheduler transports are consumed in %s but no #[AsSchedule] produces them:\n  %s\n"
            . 'Messenger cannot resolve an unknown receiver, so the worker fails to boot on the next '
            . 'restart rather than degrading — a deleted schedule takes its consume argument with it.',
            $composeFile,
            \implode("\n  ", $unbacked),
        ));
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function composeFiles(): iterable
    {
        foreach (ScheduleConsumption::COMPOSE_FILES as $composeFile) {
            yield $composeFile => [$composeFile];
        }
    }

    /**
     * Where the root compose files are reachable from, which differs by how the suite is invoked: with the
     * whole checkout present they sit beside `api/`, while inside the dev container `/app` holds only
     * `api/`, `public/` and the mounts, so they arrive through the read-only root bind mount declared in
     * `compose.dev.yaml`.
     *
     * An unresolvable directory FAILS rather than skipping. A check that quietly does nothing when its input
     * is absent is worse than no check: it reports the same green as a real pass, and the mount going away
     * is precisely the kind of silent regression this gate exists to refuse elsewhere.
     */
    private function composeDirectory(): string
    {
        $apiRoot = \dirname(__DIR__, 4);

        foreach ([\dirname($apiRoot), \dirname($apiRoot) . '/repo'] as $candidate) {
            if (\is_file($candidate . '/' . ScheduleConsumption::COMPOSE_FILES[0])) {
                return $candidate;
            }
        }

        $this->fail(
            'The root compose files are not reachable, so this gate cannot check anything. Inside the '
            . 'container they come from the read-only `./` bind mount at /app/repo declared in '
            . 'compose.dev.yaml — restore it rather than relaxing this failure into a skip.',
        );
    }
}
