<?php

declare(strict_types=1);

namespace Erpify\Tests\Unit\Gate;

use Erpify\Tests\Support\ScheduleConsumption;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use ReflectionClassConstant;

/**
 * Static gate over the one property that makes "this control is scheduled" falsifiable: every
 * `#[AsSchedule]` in `api/src` must have its derived `scheduler_*` transport named in a `messenger:consume`
 * command of BOTH root compose files.
 *
 * Nothing else in the repo checks it, and nothing at runtime complains. Symfony's `AddScheduleMessengerPass`
 * creates `messenger.transport.scheduler_<name>` from the attribute alone, so the schedule registers, the
 * container compiles, deptrac passes and every test is green while the ticks are generated by nobody and
 * consumed by nobody. A scheduled compliance control that ships dead is indistinguishable from one that
 * ships working right up until the day it was supposed to catch something.
 *
 * The replica assertions cover the second half of the same invariant. Naming the right service is worth
 * nothing if that service runs twice: ticks come from an in-process clock and `Checkpoint::acquire()` returns
 * true unconditionally without a `->lock()`. The durable checkpoint pool shares state rather than exclusion,
 * so a second replica *can* duplicate a tick rather than always doing so — `MessageGenerator` re-reads the
 * shared pool each poll and suppresses one the other replica already saved, leaving a window between the
 * winner's `acquire()` and its `save()`, which runs after the handler. That window is widest exactly where it
 * costs most: `NotifyLockedIdentitiesMessage` holds it open for an SMTP exchange and mails a person.
 *
 * What a green run does NOT prove, and the distinction matters because this gate is the evidence behind a
 * requirement that alarms have to arrive: it proves a transport name appears in a consume command, and that
 * no root compose file gives that consumer more than one replica. It does not prove the worker is running,
 * that the service is deployed, that `--time-limit` is sane, that the schedule's period is right, or that
 * anything ever reached a log. Presence of the name is the floor, not the guarantee.
 *
 * **And the pin binds the file, never the deploy.** Measured by running it, not by planning it: with two
 * otherwise identical services — one declaring `deploy.replicas: 1`, one declaring no count —
 * `docker compose up -d --scale <service>=2` left **two containers running for each**, exit 0. The
 * declaration is a default and a statement of intent; Compose does not treat it as a ceiling. So this gate
 * refuses a duplicated clock written into the repository — the vector that leaves a diff — and says nothing
 * about one asked for on a command line, which leaves no trace here. Closing that second vector needs
 * `->lock()`, hence `symfony/lock`; declined in #261, whose closing comment carries this asymmetry as the
 * recorded cost.
 *
 * One committed shape does evade it: a service using `extends` inherits the consume command without
 * declaring one of its own, and this sweep keys on a literal `command`. Nothing in the tree uses `extends`
 * today, and it is named here rather than guarded because a rule for a shape nobody writes is speculative —
 * but a reader must not mistake the green for coverage of it.
 *
 * The derivation rules live in {@see ScheduleConsumption} and their falsifiability in
 * {@see ScheduleConsumptionRulesGateTest}; this class is the assertions over the real tree.
 *
 * @internal
 */
#[CoversNothing]
final class ScheduleConsumptionGateTest extends TestCase
{
    public const string FAILURE_PREAMBLE
        = 'A schedule proves nothing by declaring itself. Symfony creates its transport from the attribute, '
        . 'so a schedule whose transport no `messenger:consume` command names compiles, registers and ships '
        . 'DEAD with every gate green — which is why "it is scheduled" is not a claim this repo lets anyone '
        . 'make without this check.';

    #[Test]
    public function theTreeDeclaresAtLeastOneSchedule(): void
    {
        // Without this the gate is vacuous: an empty sweep satisfies every assertion below, so a broken
        // attribute pattern or a moved source root would report success while checking nothing at all.
        $this->assertNotEmpty(
            ScheduleConsumption::declaredScheduleNames(),
            'No #[AsSchedule] was found under api/src. Either the tree lost every schedule or this gate '
            . 'stopped being able to see them — both make its green meaningless.',
        );
    }

    #[Test]
    #[DataProvider('composeFiles')]
    public function everyDeclaredScheduleHasItsTransportConsumed(string $composeFile): void
    {
        $path = $this->composeDirectory() . '/' . $composeFile;
        // A compose file added to the sweep without naming which service may consume a scheduler transport
        // would otherwise be checked against nothing at all.
        $this->assertArrayHasKey($composeFile, ScheduleConsumption::SCHEDULER_CONSUMER);
        $consumer = ScheduleConsumption::SCHEDULER_CONSUMER[$composeFile];
        $consumed = ScheduleConsumption::consumedTransportsByServiceIn($path)[$consumer] ?? [];

        $missing = [];

        foreach (ScheduleConsumption::declaredScheduleNames() as $scheduleName) {
            $transport = ScheduleConsumption::transportOf($scheduleName);

            if (!\in_array($transport, $consumed, true)) {
                $missing[] = $transport;
            }
        }

        $this->assertSame([], $missing, self::FAILURE_PREAMBLE . "\n" . \sprintf(
            "These schedule transports are not consumed by `%s` in %s:\n  %s\nAdd them to its "
            . '`messenger:consume` command.',
            $consumer,
            $composeFile,
            \implode("\n  ", $missing),
        ));
    }

    #[Test]
    #[DataProvider('composeFiles')]
    public function noOtherServiceConsumesASchedulerTransport(string $composeFile): void
    {
        // Presence is not the invariant; the pairing is. Every tick comes from an in-process clock, so a
        // scheduler transport consumed by the horizontally scalable pool emits one per replica — N
        // reconciliations a day instead of one. `compose.prod.yaml` says exactly this beside `replicas: 1`,
        // and nothing enforced it: a transport moved onto the wrong service satisfied a file-wide scan just
        // as well as correct wiring.
        // A compose file added to the sweep without naming which service may consume a scheduler transport
        // would otherwise be checked against nothing at all.
        $this->assertArrayHasKey($composeFile, ScheduleConsumption::SCHEDULER_CONSUMER);
        $consumer = ScheduleConsumption::SCHEDULER_CONSUMER[$composeFile];
        $byService = ScheduleConsumption::consumedTransportsByServiceIn(
            $this->composeDirectory() . '/' . $composeFile,
        );

        $misplaced = [];

        foreach ($byService as $service => $transports) {
            if ($service === $consumer) {
                continue;
            }

            foreach ($transports as $transport) {
                if (\str_starts_with($transport, 'scheduler_')) {
                    $misplaced[] = $service . ' → ' . $transport;
                }
            }
        }

        $this->assertSame([], $misplaced, \sprintf(
            "These scheduler transports are consumed by a service other than `%s` in %s:\n  %s\n"
            . 'Scheduler ticks are generated per process, so any service that can run more than one '
            . 'replica turns one scheduled run into one per replica.',
            $consumer,
            $composeFile,
            \implode("\n  ", $misplaced),
        ));
    }

    #[Test]
    #[DataProvider('composeFiles')]
    public function noConsumeCommandNamesATransportNoScheduleProduces(string $composeFile): void
    {
        $unbacked = ScheduleConsumption::unbackedSchedulerTransportsIn(
            $this->composeDirectory() . '/' . $composeFile,
            ScheduleConsumption::declaredScheduleNames(),
        );

        $this->assertSame([], $unbacked, \sprintf(
            "These scheduler transports are consumed in %s but no #[AsSchedule] produces them:\n  %s\n"
            . 'Messenger cannot resolve an unknown receiver, so the worker fails to boot on the next '
            . 'restart rather than degrading — a deleted schedule takes its consume argument with it.',
            $composeFile,
            \implode("\n  ", $unbacked),
        ));
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function composeFiles(): iterable
    {
        foreach (ScheduleConsumption::COMPOSE_FILES as $composeFile) {
            yield $composeFile => [$composeFile];
        }
    }

    #[Test]
    public function theOnlyPermittedReplicaCountIsOne(): void
    {
        // The invariant reduces to this constant, and without pinning it the whole axis is two coordinated
        // edits away from vacuous: raise it to 2, raise the compose file to 2, and every assertion below
        // stays green over a duplicated clock — with the falsification fixture, which hard-codes 2, quietly
        // switching from modelling a violation to modelling a compliant service.
        //
        // Read through reflection rather than named directly: PHPStan resolves a class constant to its
        // literal value and reports the comparison as always-true, which would make the one assertion that
        // guards the constant the one assertion the type checker forbids.
        $pinned = (new ReflectionClassConstant(ScheduleConsumption::class, 'SCHEDULER_CONSUMER_REPLICAS'))
            ->getValue()
        ;

        $this->assertSame(1, $pinned);
    }

    #[Test]
    #[DataProvider('provideTheSchedulerConsumerNeverDeclaresMoreThanOneReplicaCases')]
    public function theSchedulerConsumerNeverDeclaresMoreThanOneReplica(string $composeFile): void
    {
        $consumer = ScheduleConsumption::replicaConsumerOf($composeFile);
        $declared = ScheduleConsumption::declaredReplicasOf(
            $this->composeDirectory() . '/' . $composeFile,
            $consumer,
        );

        // Only `DEPLOYED_COMPOSE_FILE` is required to state a count; the other two are held to not
        // contradicting it, and Compose supplies the one when they say nothing.
        if (null === $declared) {
            $this->assertNotSame(ScheduleConsumption::DEPLOYED_COMPOSE_FILE, $composeFile);

            return;
        }

        $this->assertSame(ScheduleConsumption::SCHEDULER_CONSUMER_REPLICAS, $declared, \sprintf(
            'Service `%s` in %s declares %d replicas, and only %d is permitted. Every tick comes from an '
            . 'in-process clock and no schedule carries `->lock()`, so a second replica can duplicate a tick '
            . 'rather than share it — and one of the nine mails a person. A count of 0 fails here too: a '
            . 'scheduler nobody runs is the same nine controls missing, reported by nothing.',
            $consumer,
            $composeFile,
            $declared,
            ScheduleConsumption::SCHEDULER_CONSUMER_REPLICAS,
        ));
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function provideTheSchedulerConsumerNeverDeclaresMoreThanOneReplicaCases(): iterable
    {
        foreach (\array_keys(ScheduleConsumption::REPLICA_SCOPE) as $composeFile) {
            yield $composeFile => [$composeFile];
        }
    }

    #[Test]
    public function theDeployedComposeFilePinsTheSchedulerConsumerInWriting(): void
    {
        // Through the lookup rather than the offset: pairing the two literals inline lets PHPStan resolve
        // it, which turns any guard on the pairing into an always-true it refuses — and leaves the pairing
        // itself unguarded. Measured: with the deployed file dropped from the map, the inline form kept
        // `php.stan` at 0 and the suite green.
        $composeFile = ScheduleConsumption::DEPLOYED_COMPOSE_FILE;
        $consumer = ScheduleConsumption::replicaConsumerOf($composeFile);

        $this->assertNotNull(
            ScheduleConsumption::declaredReplicasOf($this->composeDirectory() . '/' . $composeFile, $consumer),
            \sprintf(
                'Service `%s` in %s declares no replica count. Compose defaults to one either way, which is '
                . 'exactly the problem: the invariant then rests on a default nobody chose and no reader can '
                . 'see, in the file a deploy applies. Write `deploy.replicas: %d`.',
                $consumer,
                $composeFile,
                ScheduleConsumption::SCHEDULER_CONSUMER_REPLICAS,
            ),
        );
    }

    /**
     * Where the root compose files are reachable from, which differs by how the suite is invoked: with the
     * whole checkout present they sit beside `api/`, while inside the dev container `/app` holds only
     * `api/`, `public/` and the mounts, so they arrive through the read-only root bind mount declared in
     * `compose.dev.yaml`.
     *
     * An unresolvable directory FAILS rather than skipping. A check that quietly does nothing when its input
     * is absent is worse than no check: it reports the same green as a real pass, and the mount going away
     * is precisely the kind of silent regression this gate exists to refuse elsewhere.
     */
    private function composeDirectory(): string
    {
        $apiRoot = \dirname(__DIR__, 3);

        foreach ([\dirname($apiRoot), \dirname($apiRoot) . '/repo'] as $candidate) {
            if (\is_file($candidate . '/' . ScheduleConsumption::COMPOSE_FILES[0])) {
                return $candidate;
            }
        }

        $this->fail(
            'The root compose files are not reachable, so this gate cannot check anything. Inside the '
            . 'container they come from the read-only `./` bind mount at /app/repo declared in '
            . 'compose.dev.yaml — restore it rather than relaxing this failure into a skip.',
        );
    }
}
