name: Full setup
description: Node + Docker
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: "24"
        cache: npm
        cache-dependency-path: pwa/package-lock.json

    - uses: docker/setup-buildx-action@v4
